class CCurrency {
  static List<List<String>> data = [
    ['AED', 'United Arab Emirates Dirham', 'ae'],
    ['BHD', 'Bahraini Dinar', 'bh'],
    ['BIF', 'Burundian Franc', 'bf'],
    ['BRL', 'Brazilian Real', 'br'],
    ['BSD', 'Bahamian Dollar', 'bd'],
    ['CAD', 'Canadian Dollar', 'ca'],
    ['COP', 'Colombian Peso', 'co'],
    ['CRC', 'Costa Rican Colón', 'cr'],
    ['EGP', 'Egyptian Pound', 'eg'],
    ['ERN', 'Eritrean Nakfa', 'er'],
    ['ETB', 'Ethiopian Birr', 'et'],
    ['EUR', 'Euro', 'fi'],
    ['GBP', 'British Pound Sterling', 'gb'],
    ['GTQ', 'Guatemalan Quetzal', 'gt'],
    ['INR', 'Indian Rupee', 'in'],
    ['IQD', 'Iraqi Dinar', 'ir'],
    ['JPY', 'Japanese Yen', 'jp'],
    ['LRD', 'Liberian Dollar', 'li'],
    ['MXN', 'Mexican Peso', 'me'],
    ['MYR', 'Malaysian Ringgit', 'ma'],
    ['MZN', 'Mozambican Metical', 'mo'],
    ['NGN', 'Nigerian Naira', 'ng'],
    ['NZD', 'New Zealand Dollar', 'nz'],
    ['RUB', 'Russian Ruble', 'ru'],
    ['SAR', 'Saudi Riyal', 'sa'],
    ['USD', 'United States Dollar', 'us'],
  ];
}
